// This file will be auto-generated by Supabase CLI
// npx supabase gen types typescript --project-id <your-project-id> > src/integrations/supabase/types.ts

export type Json = | string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  // ... will be filled in later
};
